# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-09-09 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200720_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='是否为管理员'),
        ),
    ]
